### ISSUE TITLE
Error: Option 'position_endstop' in section 'stepper_z' must be specified.

### ISSUE THREAD

**Issue by tralamazza** [jrymk/q1pro-mods#1]
Effect: Printer is halted.

Firmware: 4.4.24

The original file has a value `position_endstop:-0.2`, while the provided config has this commented out `#position_endstop: 2.600`.

**Comment by jrymk** [comment]
It is likely because I have used the Z_OFFSET_APPLY_ENDSTOP to set the origin for the inductive sensor for preliminary homing, and it has updated the save config section, causing the entries on the top to be commented out. I try to make it more inline with the actual value. For your information, my actual trigger point for the inductive probe is like so: 
```
#*# [stepper_z]
#*# position_endstop = 2.519
```
Qidi setting it to -0.2 means that when you manually jog to Z=0, the nozzle would be over 2mm from the bed. This does prevent some accidents from happening, and it should only update to the appropriate value after the get_zoffset procedure. But this isn't technically correct, so I have omitted their implementation.

You may simply uncomment the line, perform GET_ZOFFSET, and then Z_OFFSET_APPLY_ENDSTOP to make the endstop position reflect the actual probe trigger point.

**Comment by tralamazza** [comment]
Thank you for the detailed answer. I will take some time to fully understand the implications.
